# Generated by Django 3.2.8 on 2021-10-18 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default='', max_length=36)),
                ('name', models.CharField(default='', max_length=256)),
                ('rarity', models.CharField(default='', max_length=8)),
                ('usd', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('usd_foil', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('usd_etched', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('eur', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('eur_foil', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('tix', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('img_id', models.CharField(default='', max_length=10)),
                ('mana_cost', models.CharField(default='', max_length=46)),
                ('cmc', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=8, null=True)),
                ('type_line', models.CharField(default='', max_length=80)),
                ('oracle_text', models.CharField(default='', max_length=800)),
                ('power', models.CharField(default='', max_length=3)),
                ('toughness', models.CharField(default='', max_length=3)),
                ('colors', models.CharField(default='', max_length=25)),
                ('keywords', models.CharField(default='', max_length=128)),
                ('flavor_text', models.CharField(default='', max_length=500)),
                ('booster', models.BooleanField(default=False)),
                ('edhrec_rank', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(default='', max_length=256)),
                ('set_codename', models.CharField(default='', max_length=256)),
                ('set_name', models.CharField(default='', max_length=256)),
                ('set_type', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('quantity', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='tcgplaya.profile')),
                ('card', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tcgplaya.card')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='tcgplaya.profile')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cardset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tcgplaya.cardset'),
        ),
    ]
