# Generated by Django 3.2.8 on 2021-10-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcgplaya', '0002_alter_cardlisting_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='img_id',
        ),
        migrations.AddField(
            model_name='card',
            name='img_uri',
            field=models.CharField(default='', max_length=100),
        ),
    ]
